FROM python
LABEL author="xuqinghan"
LABEL purpose = 'taiga-backend'

# step by step following the offical doc:
# https://taigaio.github.io/taiga-doc/dist/setup-production.html 
ENV PYTHONIOENCODING=utf-8

RUN apt update
RUN apt install -y build-essential binutils-doc autoconf flex bison libjpeg-dev
RUN apt install -y libfreetype6-dev zlib1g-dev libzmq3-dev libgdbm-dev libncurses5-dev
RUN apt install -y automake libtool libffi-dev curl git tmux gettext
RUN apt install -y nginx
RUN apt install -y libxml2-dev libxslt-dev
RUN apt install -y libssl-dev libffi-dev
RUN apt install circus

RUN pip install setuptools
RUN pip install gunicorn

RUN mkdir -p {{BACKEND_SRC_CONTAINER}}
WORKDIR {{BACKEND_SRC_CONTAINER}}
#only copy requirements.txt. other code will be mounted by -v
COPY ./src/taiga-back/requirements.txt ./requirements.txt


RUN pip install -r ./requirements.txt

#add user taiga
RUN adduser taiga
RUN adduser taiga sudo



#USER taiga
RUN mkdir -p {{LOGS_CONTAINER}}
RUN mkdir -p {{BACKEND_MEDIA_CONTAINER}}
RUN mkdir -p {{BACKEND_STATIC_CONTAINER}}
RUN chown -R taiga {{BACKEND_MEDIA_CONTAINER}}
RUN chown -R taiga {{BACKEND_STATIC_CONTAINER}}

# .sh and .py for connect pg_db and first run manager.py
RUN mkdir -p /scripts
COPY ./scripts /scripts
RUN chown -R taiga /scripts
RUN chmod +x /scripts/entrypoint.sh

COPY wait-for-postgres.sh /wait-for-postgres.sh
#RUN chown -R taiga /wait-for-postgres.sh
RUN chmod +x /wait-for-postgres.sh

# Setup circus
COPY taiga.ini /etc/circus/conf.d/taiga.ini
#RUN service circusd restart
RUN pip install django-environ

COPY ./src/taiga-back {{BACKEND_SRC_CONTAINER}}
RUN chown -R taiga {{BACKEND_SRC_CONTAINER}}
#USER taiga
#first run
ENTRYPOINT ["/scripts/entrypoint.sh"]

