version: '3.4'

services:
    {{POSTGRES_SERVER}}:
        image: postgres
        environment:
            POSTGRES_USER: {{POSTGRES_USER}}
            POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
            
        volumes:
            - {{POSTGRES_VOLUMN_PATH}}:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    # redis:
    #     image: redis

    {{RABBITMQ_SERVER}}:
        #restart: always
        #build: rabbitmq/
        image: rabbitmq:3-management
        hostname: {{RABBITMQ_HOSTNAME}}
        environment:
            RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
            #RABBITMQ_NODENAME: taiga
            RABBITMQ_DEFAULT_USER: {{RABBITMQ_DEFAULT_USER}}
            RABBITMQ_DEFAULT_PASS: {{RABBITMQ_DEFAULT_PASS}}
            #RABBITMQ_DEFAULT_VHOST: taiga
        ports:
            - 15672:15672
            - 5672:5672

    {{API_SERVER}}:
        build: backend/
        volumes:
            - {{LOGS_HOST}}:{{LOGS_CONTAINER}}
            - {{BACKEND_MEDIA_HOST}}:{{BACKEND_MEDIA_CONTAINER}}
            - {{BACKEND_STATIC_HOST}}:{{BACKEND_STATIC_CONTAINER}}
        environment:
        # - DJANGO_ALLOWED_HOSTS=example.com,example2.com
        # Must be in lowercase, because we are using in a json file <frontend> (conf.json)
        # - TAIGA_PUBLIC_REGISTER_ENABLED=false
        # - TAIGA_SSL=True
            TAIGA_HOSTNAME: {{TAIGA_HOSTNAME}}
        # - TAIGA_SKIP_DB_CHECK=True
        # command: ['gunicorn', '--worker-class', 'gevent', '--workers', '10', '-b', '0.0.0.0:8000', 'taiga.wsgi']
        ports:
            - {{BACKEND_PORT}}:{{BACKEND_PORT}}
        depends_on:
            - {{POSTGRES_SERVER}}
        # entrypoint: ["~/wait-for-postgres.sh", "{{POSTGRES_SERVER}}", "~/scripts/entrypoint.sh"]
        command: ['gunicorn', '-b', '0.0.0.0:{{BACKEND_PORT}}', 'taiga.wsgi']
        #command: ["/usr/local/bin/circusd", "/etc/circus/circusd.ini"]

    frontend:
        build: frontend/
        volumes:
            #- {{API_SERVER}}:ro
            - {{FRONTEND_SRC_HOST}}:{{FRONTEND_SRC_CONTAINER}}
            - {{LOGS_HOST}}:{{LOGS_CONTAINER}}
            - {{BACKEND_MEDIA_HOST}}:{{BACKEND_MEDIA_CONTAINER}}
            - {{BACKEND_STATIC_HOST}}:{{BACKEND_STATIC_CONTAINER}}

        # environment:
        # Must be in lowercase, because we are using in a json file (conf.json)
        #   - TAIGA_DEBUG=true
        #   - TAIGA_API_URL="http://example.com/api/v1/"
        #   - TAIGA_EVENTS_URL="ws://example.com/events"
        # Must be in lowercase, because we are using in a json file (conf.json)
        #   - TAIGA_PUBLIC_REGISTER_ENABLED=false
        #   - DEFAULT_LANGUAGE="en"
        ports:
            - 80:80

        #command: ["nginx", "-g", "daemon off;"]
        depends_on:
        # It would be better to add 'postgres' to 'depends_on' on 'backend' service
        # but 'celeryworker' extends 'backend' and we cannot extend a service
        # if it is using 'depends_on'.
            - {{POSTGRES_SERVER}}
            - {{API_SERVER}}

    # celeryworker:
    #     image: taigadockercompose_api
    #     entrypoint: []
    #     command: ['celery', '-A', 'taiga', 'worker', '-c', '4', '--loglevel', 'info']
    #     # command: ['celery', '-A', 'taiga', 'worker', '-P', 'gevent', '-c', '4', '--loglevel', 'info']
    #     depends_on:
    #     #- redis
    #         - {{RABBITMQ_SERVER}}

    {{EVENTS_SERVER}}:
        build: events/
        volumes:
            #- {{EVENTS_SRC_HOST}}:{{EVENTS_SRC_CONTAINER}}
            - {{LOGS_HOST}}:{{LOGS_CONTAINER}}
        # entrypoint: ['/scripts/entrypoint.sh']
        # command: ['coffee', 'index.coffee']
        ports:
            - {{EVENTS_PORT}}:{{EVENTS_PORT}}
        depends_on:
            - {{RABBITMQ_SERVER}}
